  - name: Create database user and database
      postgresql_user:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        login_user: postgres
        login_password: postgres
        login_host: localhost
        login_unix_socket: /var/run/postgresql
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        login_user: postgres
        login_password: postgres
        login_host: localhost
        login_unix_socket: /var/run/postgresql

    - name: Restore database on another server
      postgresql_user:
        db: "{{ restore_db_name }}"
        name: "{{ restore_db_user }}"
        password: "{{ restore_db_password }}"
        login_user: postgres
        login_password: postgres
        login_host: localhost
        login_unix_socket: /var/run/postgresql
      postgresql_db:
        name: "{{ restore_db_name }}"
        owner: "{{ restore_db_user }}"
        login_user: postgres
        login_password: postgres
        login_host: localhost
        login_unix_socket: /var/run/postgresql
      postgresql_restore:
        db: "{{ restore_db_name }}"
        login_user: "{{ restore_db_user }}"
        login_password: "{{ restore_db_password }}"
        login_host: localhost
        login_unix_socket: /var/run/postgresql
        filename: "{{ restore_file }}"
